export const VEHICLES = [
  {
    id: 1,
    make: 'Toyota',
    model: 'Camry',
    year: 2020,
    price: 18900,
    mileage: 45000,
    fuel: 'Gasoline',
    transmission: 'Automatic',
    category: 'Sedan',
    image: 'https://images.unsplash.com/photo-1621007947382-bb3c3968e3bb?w=600',
    featured: true,
    condition: 'Excellent',
    description: 'Reliable sedan with excellent fuel economy. Perfect for daily commuting.',
    features: ['Backup Camera', 'Bluetooth', 'Cruise Control', 'Power Windows'],
  },
  {
    id: 2,
    make: 'Honda',
    model: 'CR-V',
    year: 2021,
    price: 24500,
    mileage: 32000,
    fuel: 'Gasoline',
    transmission: 'Automatic',
    category: 'SUV',
    image: 'https://images.unsplash.com/photo-1568844293986-8d0400bd4745?w=600',
    featured: true,
    condition: 'Like New',
    description: 'Spacious SUV with advanced safety features. Great for families.',
    features: ['AWD', 'Lane Assist', 'Apple CarPlay', 'Sunroof'],
  },
  {
    id: 3,
    make: 'Ford',
    model: 'F-150',
    year: 2019,
    price: 28900,
    mileage: 56000,
    fuel: 'Gasoline',
    transmission: 'Automatic',
    category: 'Truck',
    image: 'https://images.unsplash.com/photo-1551830820-330a71b99659?w=600',
    featured: true,
    condition: 'Good',
    description: 'Powerful truck ready for work or play. Towing capacity of 12,000 lbs.',
    features: ['4WD', 'Towing Package', 'Running Boards', 'Bed Liner'],
  },
  {
    id: 4,
    make: 'Tesla',
    model: 'Model 3',
    year: 2022,
    price: 32900,
    mileage: 18000,
    fuel: 'Electric',
    transmission: 'Automatic',
    category: 'Electric',
    image: 'https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=600',
    featured: false,
    condition: 'Like New',
    description: 'Cutting-edge electric vehicle with autopilot capabilities.',
    features: ['Autopilot', 'Full Self-Driving', 'Glass Roof', 'Premium Audio'],
  },
  {
    id: 5,
    make: 'BMW',
    model: 'X5',
    year: 2020,
    price: 42500,
    mileage: 38000,
    fuel: 'Gasoline',
    transmission: 'Automatic',
    category: 'Luxury SUV',
    image: 'https://images.unsplash.com/photo-1555215695-3004980adade?w=600',
    featured: false,
    condition: 'Excellent',
    description: 'Luxury SUV with premium interior and exceptional performance.',
    features: ['Leather Seats', 'Panoramic Roof', 'Harman Kardon Audio', 'Air Suspension'],
  },
  {
    id: 6,
    make: 'Chevrolet',
    model: 'Silverado',
    year: 2021,
    price: 31500,
    mileage: 41000,
    fuel: 'Gasoline',
    transmission: 'Automatic',
    category: 'Truck',
    image: 'https://images.unsplash.com/photo-1570125909232-eb263c188f7e?w=600',
    featured: false,
    condition: 'Excellent',
    description: 'Full-size truck with modern technology and comfort.',
    features: ['Trailering Package', 'Wireless Charging', 'Bose Audio', 'Remote Start'],
  },
  {
    id: 7,
    make: 'Toyota',
    model: 'Prius',
    year: 2021,
    price: 21500,
    mileage: 29000,
    fuel: 'Hybrid',
    transmission: 'Automatic',
    category: 'Hybrid',
    image: 'https://images.unsplash.com/photo-1617788138017-80ad40651399?w=600',
    featured: false,
    condition: 'Like New',
    description: 'Industry-leading hybrid with 50+ MPG fuel efficiency.',
    features: ['Hybrid Synergy Drive', 'LED Headlights', 'Smart Key', 'Climate Control'],
  },
  {
    id: 8,
    make: 'Jeep',
    model: 'Wrangler',
    year: 2020,
    price: 27500,
    mileage: 42000,
    fuel: 'Gasoline',
    transmission: 'Manual',
    category: 'SUV',
    image: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=600',
    featured: false,
    condition: 'Good',
    description: 'Iconic off-road SUV ready for adventure. Removable top.',
    features: ['4x4', 'Removable Top', 'Off-Road Tires', 'Winch Ready'],
  },
  {
    id: 9,
    make: 'Honda',
    model: 'Accord',
    year: 2020,
    price: 20500,
    mileage: 38000,
    fuel: 'Gasoline',
    transmission: 'Automatic',
    category: 'Sedan',
    image: 'https://images.unsplash.com/photo-1617469767053-d3b523a0b982?w=600',
    featured: false,
    condition: 'Excellent',
    description: 'Midsize sedan with turbocharged engine and spacious interior.',
    features: ['Turbo Engine', 'Honda Sensing', 'Heated Seats', 'Dual-Zone Climate'],
  },
  {
    id: 10,
    make: 'Nissan',
    model: 'Leaf',
    year: 2021,
    price: 19500,
    mileage: 22000,
    fuel: 'Electric',
    transmission: 'Automatic',
    category: 'Electric',
    image: 'https://images.unsplash.com/photo-1593941707882-a5bba14938c7?w=600',
    featured: false,
    condition: 'Like New',
    description: 'Affordable electric car with 200+ mile range.',
    features: ['ProPILOT Assist', 'e-Pedal', 'Quick Charge', 'NissanConnect'],
  },
  {
    id: 11,
    make: 'Hyundai',
    model: 'Sonata Hybrid',
    year: 2022,
    price: 23500,
    mileage: 15000,
    fuel: 'Hybrid',
    transmission: 'Automatic',
    category: 'Hybrid',
    image: 'https://images.unsplash.com/photo-1611365892117-00ac5ef43c90?w=600',
    featured: false,
    condition: 'Like New',
    description: 'Stylish hybrid with solar roof and advanced safety.',
    features: ['Solar Roof', 'Blind Spot Monitor', 'Wireless Android Auto', 'Digital Key'],
  },
  {
    id: 12,
    make: 'Mercedes-Benz',
    model: 'C-Class',
    year: 2021,
    price: 38500,
    mileage: 25000,
    fuel: 'Gasoline',
    transmission: 'Automatic',
    category: 'Luxury',
    image: 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=600',
    featured: false,
    condition: 'Excellent',
    description: 'Compact luxury sedan with premium finishes.',
    features: ['MBUX', 'Burmester Audio', 'Ambient Lighting', 'MB-Tex Interior'],
  },
]

export const CATEGORIES = ['All', 'Sedan', 'SUV', 'Truck', 'Electric', 'Hybrid', 'Luxury', 'Luxury SUV']

export const PRICE_RANGES = [
  { value: 'all', label: 'All Prices' },
  { value: 'under20', label: 'Under $20K' },
  { value: '20to30', label: '$20K - $30K' },
  { value: 'over30', label: 'Over $30K' },
]
