export const VEHICLES = [
  {
    id: 1,
    make: 'Toyota',
    model: 'Camry',
    year: 2018,
    price: 14900,
    mileage: 68400,
    fuel: 'Gasoline',
    transmission: 'Automatic',
    category: 'Sedan',
    image: 'https://images.unsplash.com/photo-1621007947382-bb3c3968e3bb?w=600',
    featured: true,
    condition: 'Good',
    description: 'Daily-driver sedan with a clean local history. Solid commute car for Lancaster roads.',
    features: ['Backup Camera', 'Bluetooth', 'Cruise Control', 'Power Windows'],
  },
  {
    id: 2,
    make: 'Honda',
    model: 'CR-V',
    year: 2019,
    price: 18900,
    mileage: 54200,
    fuel: 'Gasoline',
    transmission: 'Automatic',
    category: 'SUV',
    image: 'https://images.unsplash.com/photo-1568844293986-8d0400bd4745?w=600',
    featured: true,
    condition: 'Excellent',
    description: 'One-owner compact SUV with AWD. Fits a family without jumping into luxury pricing.',
    features: ['AWD', 'Honda Sensing', 'Apple CarPlay', 'Heated Seats'],
  },
  {
    id: 3,
    make: 'Ford',
    model: 'F-150',
    year: 2017,
    price: 21900,
    mileage: 89600,
    fuel: 'Gasoline',
    transmission: 'Automatic',
    category: 'Truck',
    image: 'https://images.unsplash.com/photo-1551830820-330a71b99659?w=600',
    featured: true,
    condition: 'Good',
    description: 'Work-ready half-ton with a towing package. Typical independent-lot truck, not a showpiece.',
    features: ['4WD', 'Towing Package', 'Running Boards', 'Bed Liner'],
  },
  {
    id: 4,
    make: 'Honda',
    model: 'Civic',
    year: 2018,
    price: 12900,
    mileage: 71200,
    fuel: 'Gasoline',
    transmission: 'Automatic',
    category: 'Sedan',
    image: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=600',
    featured: false,
    condition: 'Good',
    description: 'Compact sedan with Honda Sensing. Easy on gas and insurance.',
    features: ['Honda Sensing', 'Bluetooth', 'Backup Camera', 'USB Ports'],
  },
  {
    id: 5,
    make: 'Chevrolet',
    model: 'Equinox',
    year: 2018,
    price: 15400,
    mileage: 76400,
    fuel: 'Gasoline',
    transmission: 'Automatic',
    category: 'SUV',
    image: 'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=600',
    featured: false,
    condition: 'Good',
    description: 'Midsize Chevy crossover with Apple CarPlay and a roomy cargo area.',
    features: ['Apple CarPlay', 'Backup Camera', 'Remote Start', 'Cloth Seats'],
  },
  {
    id: 6,
    make: 'Chevrolet',
    model: 'Silverado',
    year: 2016,
    price: 19900,
    mileage: 98400,
    fuel: 'Gasoline',
    transmission: 'Automatic',
    category: 'Truck',
    image: 'https://images.unsplash.com/photo-1570125909232-eb263c188f7e?w=600',
    featured: false,
    condition: 'Good',
    description: 'Full-size Chevy truck for hauling and weekend projects. Miles are honest for the year.',
    features: ['4WD', 'Trailering Package', 'Crew Cab', 'Tow Hitch'],
  },
  {
    id: 7,
    make: 'Toyota',
    model: 'Prius',
    year: 2017,
    price: 13900,
    mileage: 81200,
    fuel: 'Hybrid',
    transmission: 'Automatic',
    category: 'Hybrid',
    image: 'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=600',
    featured: false,
    condition: 'Excellent',
    description: 'Hybrid hatch with 50-MPG-class economy. Battery health checked on arrival.',
    features: ['Hybrid Synergy Drive', 'Backup Camera', 'Smart Key', 'Climate Control'],
  },
  {
    id: 8,
    make: 'Jeep',
    model: 'Wrangler',
    year: 2016,
    price: 21500,
    mileage: 87800,
    fuel: 'Gasoline',
    transmission: 'Manual',
    category: 'SUV',
    image: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=600',
    featured: false,
    condition: 'Good',
    description: 'Two-door Jeep Wrangler with 4x4. Independent-lot miles, not a trail-rig build.',
    features: ['4x4', 'Removable Top', 'Off-Road Tires', 'Uconnect'],
  },
  {
    id: 9,
    make: 'Honda',
    model: 'Accord',
    year: 2017,
    price: 13500,
    mileage: 79400,
    fuel: 'Gasoline',
    transmission: 'Automatic',
    category: 'Sedan',
    image: 'https://images.unsplash.com/photo-1617469767053-d3b523a0b982?w=600',
    featured: false,
    condition: 'Excellent',
    description: 'Midsize Honda sedan with a spacious cabin. Inspected and ready for a test drive.',
    features: ['Honda Sensing', 'Bluetooth', 'Heated Seats', 'Dual-Zone Climate'],
  },
  {
    id: 10,
    make: 'Nissan',
    model: 'Altima',
    year: 2018,
    price: 11900,
    mileage: 77600,
    fuel: 'Gasoline',
    transmission: 'Automatic',
    category: 'Sedan',
    image: 'https://images.unsplash.com/photo-1619767886558-efdc259cde1a?w=600',
    featured: false,
    condition: 'Good',
    description: 'Affordable Nissan sedan under $12k. Straightforward commuter with backup camera.',
    features: ['Backup Camera', 'Bluetooth', 'Cruise Control', 'Keyless Entry'],
  },
  {
    id: 11,
    make: 'Hyundai',
    model: 'Elantra',
    year: 2019,
    price: 9900,
    mileage: 69200,
    fuel: 'Gasoline',
    transmission: 'Automatic',
    category: 'Sedan',
    image: 'https://images.unsplash.com/photo-1550355291-bbee04a92027?w=600',
    featured: false,
    condition: 'Good',
    description: 'Entry-price Hyundai sedan on the lot. Remaining factory warranty may transfer — ask in person.',
    features: ['Android Auto', 'Backup Camera', 'Bluetooth', 'USB Ports'],
  },
  {
    id: 12,
    make: 'Nissan',
    model: 'Rogue',
    year: 2019,
    price: 16400,
    mileage: 62700,
    fuel: 'Gasoline',
    transmission: 'Automatic',
    category: 'SUV',
    image: 'https://images.unsplash.com/photo-1606016159991-dfe4f2746ad5?w=600',
    featured: false,
    condition: 'Excellent',
    description: 'Compact Nissan SUV with AWD. Easy parking around Lancaster and plenty of cargo space.',
    features: ['AWD', 'Apple CarPlay', 'Backup Camera', 'Blind Spot Warning'],
  },
]

export const CATEGORIES = ['All', 'Sedan', 'SUV', 'Truck', 'Hybrid']

export const PRICE_RANGES = [
  { value: 'all', label: 'All Prices' },
  { value: 'under20', label: 'Under $20K' },
  { value: '20to30', label: '$20K - $30K' },
  { value: 'over30', label: 'Over $30K' },
]
